MVC-Frontend/Models/Coin.cs
namespace MVC_Frontend.Models
{
    public class Coin
    {
        public int Id { get; set; }
        public string Symbol { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public double Change { get; set; }
        public double PChange { get; set; }
        public double MarketCap { get; set; }
        public double Volume { get; set; }
        public double Volume24H { get; set; }
        public double TotalVolume24H { get; set; }
        public double CirculatingSupply { get; set; }

        // navigation properties
        public int SnapId { get; set; }
        public virtual MarketSnapshot MarketSnapshot { get; set; }
    }
}

MVC-Frontend/Models/MarketSnapshot.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MVC_Frontend.Models
{
    public class MarketSnapshot
    {
        [Key]
        public int SnapId { get; set; }
        public DateTime SnapTime { get; set; }

        public virtual List<Coin> Coins { get; set; }
    }
}

MVC-Frontend/Models/MarketSnapshotContext.cs
using System.Data.Entity;

namespace MVC_Frontend.Models
{
    public class MarketSnapshotContext : DbContext
    {
        public DbSet<MarketSnapshot> MarketSnapshots { get; set; }
        public DbSet<Coin> Coins { get; set; }
    }
}

MVC-Frontend/Models/Selenium/Extractor.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Text.RegularExpressions;
using OpenQA.Selenium;

namespace MVC_Frontend.Models.Selenium
{
    internal static class Extractor
    {
        public static Coin ParseCoin(List<string> properties, ReadOnlyCollection<IWebElement> values)
        {
            Coin coin = new Coin();
            var coinsProperties = new Dictionary<string, string>();

            for (var index = 0; index < values.Count; index++)
            {
                coinsProperties[properties[index]] = values[index].Text;
            }

            try
            {
                coin.Symbol = coinsProperties["Symbol"];
                coin.Name = coinsProperties["Name"];
                coin.Price = double.Parse(coinsProperties["Price (Intraday)"]);
                coin.Change = double.Parse(coinsProperties["Change"].Replace("%", ""));
                coin.PChange = double.Parse(coinsProperties["% Change"].Replace("%", ""));
                coin.MarketCap = ParseMagnitude(coinsProperties["Market Cap"]);
                coin.Volume = ParseMagnitude(coinsProperties["Volume in Currency (Since 0:00 UTC)"]);
                coin.Volume24H = ParseMagnitude(coinsProperties["Volume in Currency (24Hr)"]);
                coin.TotalVolume24H = ParseMagnitude(coinsProperties["Total Volume All Currencies (24Hr)"]);
                coin.CirculatingSupply = ParseMagnitude(coinsProperties["Circulating Supply"]);
            }
            catch
            {
                throw new Exception("Values Collation Error: Could not find Value");
            }

            return coin;
        }
        
        private static double ParseMagnitude(string s)
        {
            var input = Regex.Replace(s, "[^0-9.MBT]", "");

            // M B and T for Millions, Billions, and Trillions. (eg 142.43B	=== 142,000,000,000)
            switch (input[(input.Length - 1)])
            {
                case 'M':
                    return double.Parse(input.Replace("M", "")) * 1000000;
                case 'B':
                    return double.Parse(input.Replace("B", "")) * 1000000000;
                case 'T':
                    return double.Parse(input.Replace("T", "")) * 1000000000000;
                default:
                    try
                    {
                        return double.Parse(input);
                    }
                    catch
                    {
                        throw new Exception("Magnitude Conversion Failure");                        
                    }
            }
        }
    }
}

MVC-Frontend/Models/Selenium/Scraper.cs
using System;
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;

namespace MVC_Frontend.Models.Selenium
{
    internal static class Scraper
    {
        private static readonly IWebDriver WebDriver;

        static Scraper()
        {
            ChromeOptions option = new ChromeOptions();
            option.AddArguments("--headless", "--disable-javascript");
            WebDriver = new ChromeDriver(option);
        }

        public static List<Coin> CompileSnapshot()
        {
            const string url = "https://finance.yahoo.com/cryptocurrencies?offset=0&count=150";
            
            WebDriver.Navigate().GoToUrl(url);

            if (WebDriver.Title == string.Empty)
                throw new Exception("[Null Page Title] Probable Page-Access Fault\n- " + url + " -\n");

            var (symbols, properties) = GetTableHeads();

            var coins = new List<Coin>();

            // create a list of all coins (with respective properties)
            for (var row = 1; row < symbols.Count + 1; row++)
            {
                var xPath = "//*[@id=\"scr-res-table\"]/table/tbody/tr[" +
                            row + "]/td[position() >= 2 and not(position() > 11)]";

                var results = WebDriver.FindElements(By.XPath(xPath));

                coins.Add(Extractor.ParseCoin(properties, results));
            }

            return coins;
        }

        public static void QuitWebDriver()
        {
            WebDriver.Quit();
        }

        private static (List<string> symbols, List<string> properties) GetTableHeads()
        {
            // acquire the stock symbols (vertical table header)
            var symbols = Symbols;

            // acquire the stock properties (horizontal table header)
            var properties = Properties;

            return (symbols, properties);
        }

        private static List<string> Properties
        {
            get
            {
                var headCols =
                    WebDriver.FindElements(
                        By.XPath("//*[@id=\"scr-res-table\"]/table/thead/tr/th[*]/span"));
                var properties = new List<string>();
                foreach (IWebElement c in headCols)
                    properties.Add(c.Text);
                return properties;
            }
        }

        private static List<string> Symbols
        {
            get
            {
                var headRows =
                    WebDriver.FindElements(
                        By.XPath("//*[@id=\"scr-res-table\"]/table/tbody/tr[*]/td[2]/a"));
                var symbols = new List<string>();
                foreach (IWebElement r in headRows)
                    symbols.Add(r.Text);
                return symbols;
            }
        }
    }
}

MVC-Frontend/Controllers/SnapshotsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MVC_Frontend.Models;
using MVC_Frontend.Models.Selenium;

namespace MVC_Frontend.Controllers
{
    public class SnapshotsController : Controller
    {
        private readonly MarketSnapshotContext _context;

        public SnapshotsController()
        {
            _context = new MarketSnapshotContext();
        }

        // GET: All MarketSnapshot
        public ViewResult Index()
        {
            var snapshots = _context.MarketSnapshots.ToList();

            return View(snapshots);
        }

        public ActionResult Details(int id)
        {
            var snapshot = _context.MarketSnapshots.SingleOrDefault(c => c.SnapId == id);

            if (snapshot == null)
                return HttpNotFound();

            return View(snapshot);
        }

        // Run Selenium
        public ActionResult CompileSnapshot()
        {
            List<Coin> snapshot;
            try
            {
                snapshot = Scraper.CompileSnapshot();
                Scraper.QuitWebDriver();
            }
            catch (Exception e)
            {
                Scraper.QuitWebDriver();
                Console.WriteLine(e);
                throw;
            }

            using (var db = new MarketSnapshotContext())
            {
                // build dbContext object from the list of coin objects procured via selenium
                var marketSnapshot = new MarketSnapshot
                {
                    Coins = snapshot,
                    SnapTime = DateTime.Now
                };

                // append to database
                db.MarketSnapshots.Add(marketSnapshot);
                db.SaveChanges();
            }

            return View(snapshot);
        }
    }
}

MVC-Frontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Coin Explorer", "Index", "Snapshots", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Snapshots", "Index", "Snapshots")</li>
                    <li>@Html.ActionLink("Compile Snapshot", "CompileSnapshot", "Snapshots")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Coin Explorer</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MVC-Frontend/Views/Snapshots/CompileSnapshot.cshtml
@using MVC_Frontend.Models
@model List<MVC_Frontend.Models.Coin>

<!DOCTYPE html>
<html>
<head>
    <title>Market SnapShot</title>
</head>
<body>
<div>
    <table>
        @{
            foreach (var coin in Model)
            {
                <tr>
                    <td>@coin.Name</td>
                    <td>@coin.Price</td>
                </tr>
            };
        }
    </table>
</div>
</body>
</html>

MVC-Frontend/Views/Snapshots/Details.cshtml
@model MVC_Frontend.Models.MarketSnapshot

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>MarketSnapshot</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SnapTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SnapTime)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

MVC-Frontend/Views/Snapshots/Index.cshtml
@using MVC_Frontend.Models
@model List<MarketSnapshot>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    th {
        text-align: center
    }
</style>
<!DOCTYPE html>

<html>
<head>
    <title>All Snapshots</title>
</head>
<body>
    <div>
        <table class="table table-bordered table-hover">
            <thead>
                <tr><th colspan="2">Snapshots List</th></tr>
                <tr>
                    <td>ID</td>
                    <td>DateTime</td>
                </tr>
            </thead>
            <tbody>
                @foreach (MarketSnapshot marketSnapshot in Model)
                {
                <tr>
                    <td>@marketSnapshot.SnapId</td>
                    <td>@marketSnapshot.SnapTime</td>
                    <td><a href="Details/@marketSnapshot.SnapId">View</a></td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>